site_name: SexyCoders Docs
nav:
  - Home: index.md
  - API: 
    - Authentication: api/authentication.md
    - Token Verification: api/verify.md
    - ThirdParty:
      - Solar API: thirdparty/solar.md
      - Weather API: thirdparty/weather.md
  - Databases:
    - Managed Databases: data/managed.md
  - For Developers: 
    - Helper Commands: for_developers/helpers.md
    - Names and Versioning: for_developers/versioning.md
  - Tools:
    - Docker: tools/docker.md
    - MongoDB: tools/mongodb.md
    - APIs: tools/apis.md
    - Vue: tools/vue.md
    - Security: tools/security.md
  - CookBooks:
    - Docker API inside Container: cookbook/docker_api_in_container.md
  - CheatSheets:
    - Docker API: cheatsheets/docker_api.md
