site_name: SexyCoders Docs
nav:
  - Home: index.md
  - API: 
    - Authentication: api/authentication.md
    - Token Verification: api/verify.md
  - For Developers: 
    - Helper Commands: for_developers/helpers.md
    - Names and Versioning: for_developers/versioning.md

